from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path("reference/", views.reference_view, name="reference"),
    path("reference_delete/<int:pk>", views.reference_delete, name="reference_delete"),
    path("reference_create/", views.reference_create, name="reference_create"),
    path('reference_update/<int:pk>', views.reference_update, name='reference_update'),
    path('staff/', views.staff_view, name='staff_name'),
    path('staff_delete/<int:id>/', views.staff_delete, name='staff_delete'),
    path('staff_create/', views.staff_create, name='staff_create'),
    path('staff_update/<int:id>/', views.staff_update, name='staff_update'),
    path('cost/', views.cost_view, name='cost_name'),
    path('cost_create/', views.cost_create, name='costcreate_name'),
    path("cost_delete/<int:pk>", views.cost_delete, name="costdelete_name"),
    path('cost_update/<int:pk>/', views.cost_update, name='costupdate_name'),   
    path('output', views.output_view, name='output_name'),   
    path('output_create/', views.output_create, name='outputcreate_name'),
    path("output_delete/<int:pk>/", views.output_delete, name="outputdelete_name"),
    path('output_update/<int:pk>/', views.output_update, name='outputupdate_name'),       
    path('book_create/', views.book_create, name='bookcreate_name'),       
    path('book_delete/<int:pk>/', views.book_delete, name='bookdelete_name'),
    path('book_update/<int:pk>/', views.book_update, name='bookupdate_name'),   
    path('income', views.income_view, name='income_name'),   
    path('book/<int:book_id>/', views.book_detail, name='book_detail'),
    path('income_create/', views.income_create, name='incomecreate_name'),   
    path('income_delete/<int:pk>/', views.income_delete, name='incomedelete_name'),
    path('income_update/<int:pk>/', views.income_update, name='incomeupdate_name'),   
    path('daromad', views.daromad , name="daromad"),
    path('staff_payment_create/', views.staff_payment_create , name="staffcreate_name"),
    path('staff_payment_delete/<int:pk>/', views.staff_payment_delete, name='staffpaymentdelete_name'),
    path('staff_payment_update/<int:pk>/', views.staff_payment_update, name='staffpaymentupdate_name'),         
    path('staff_work_create/', views.staff_work_create , name="staffwork_name"),
    path('staff_work_delete/<int:pk>/', views.staff_work_delete, name='staffworkdelete_name'),
    path('staff_work_update/<int:pk>/', views.staff_work_update, name='staffworkupdate_name'),         
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]