# Generated by Django 5.1.3 on 2025-03-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book_model_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_model',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
