# Generated by Django 5.1.3 on 2025-03-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cost_model_isdeleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost_model',
            old_name='IsDeleted',
            new_name='Is_deleted',
        ),
    ]
