# Generated by Django 5.1.3 on 2025-03-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_isdeleted_cost_model_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost_model',
            old_name='Is_deleted',
            new_name='is_deleted',
        ),
    ]
