# Generated by Django 5.1.3 on 2025-03-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_is_deleted_cost_model_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_model',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='output',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff_model',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff_payments',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff_work',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
