# Generated by Django 5.1.3 on 2025-03-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_income_model_is_deleted_output_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_model',
            name='image',
            field=models.ImageField(default=1, upload_to='books/', verbose_name='Book rasmi'),
            preserve_default=False,
        ),
    ]
