# Generated by Django 5.1.3 on 2025-03-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_book_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_model',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Book rasmi'),
        ),
    ]
