# Generated by Django 5.1.3 on 2025-03-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_book_model_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_model',
            old_name='category',
            new_name='author',
        ),
    ]
