# Generated by Django 5.1.3 on 2025-03-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_category_book_model_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_model',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_category_references', to='home.reference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_model',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_author_references', to='home.reference'),
        ),
    ]
