# Generated by Django 5.1.6 on 2025-04-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_trash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trash',
        ),
    ]
