# Generated by Django 5.1.3 on 2025-04-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_income_model_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_model',
            name='created_at',
            field=models.DateField(verbose_name='sanasi'),
        ),
    ]
