# Generated by Django 5.1.6 on 2025-04-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_income_model_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
