# Generated by Django 5.1.3 on 2025-05-16 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_reference_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_model',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Kitob rasmi'),
        ),
        migrations.AlterField(
            model_name='book_model',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Kitob soni'),
        ),
        migrations.AlterField(
            model_name='cost_model',
            name='created_at',
            field=models.DateField(verbose_name='Xarid sanasi'),
        ),
        migrations.AlterField(
            model_name='cost_model',
            name='description',
            field=models.TextField(verbose_name='Xarid haqida'),
        ),
        migrations.AlterField(
            model_name='cost_model',
            name='price',
            field=models.FloatField(verbose_name='Xarid narxi'),
        ),
        migrations.AlterField(
            model_name='cost_model',
            name='quantity',
            field=models.IntegerField(verbose_name='Xarid soni'),
        ),
        migrations.AlterField(
            model_name='output',
            name='created_at',
            field=models.DateField(verbose_name='Chiqim sanasi'),
        ),
        migrations.AlterField(
            model_name='output',
            name='description',
            field=models.TextField(verbose_name='Chiqim haqida'),
        ),
        migrations.AlterField(
            model_name='output',
            name='price',
            field=models.BigIntegerField(verbose_name='Chiqim narxi'),
        ),
        migrations.AlterField(
            model_name='staff_model',
            name='experience',
            field=models.FloatField(verbose_name='Xodimning tajribasi'),
        ),
        migrations.AlterField(
            model_name='staff_payments',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Xodim Sanasi'),
        ),
        migrations.AlterField(
            model_name='staff_payments',
            name='price',
            field=models.FloatField(verbose_name='Xodim xaqqi'),
        ),
        migrations.AlterField(
            model_name='staff_payments',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.staff_model', verbose_name='Xodim'),
        ),
        migrations.AlterField(
            model_name='staff_work',
            name='price',
            field=models.FloatField(verbose_name='Xodimning xaqqi'),
        ),
        migrations.AlterField(
            model_name='staff_work',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.staff_model', verbose_name='Xodim'),
        ),
        migrations.AlterField(
            model_name='staff_work',
            name='time_work',
            field=models.IntegerField(verbose_name='Xodimning ishlagan vaqti'),
        ),
    ]
