# Generated by Django 5.1.3 on 2025-02-19 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kitob nomi')),
                ('price', models.FloatField(verbose_name='Kitob narxi')),
                ('quantity', models.IntegerField(verbose_name='Kitob soni')),
                ('description', models.TextField(verbose_name='Kitob haqida')),
            ],
        ),
        migrations.CreateModel(
            name='reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='reference nomi')),
                ('value', models.CharField(max_length=255, verbose_name='reference qiymati')),
            ],
        ),
        migrations.CreateModel(
            name='Cost_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Cost narxi')),
                ('quantity', models.IntegerField(verbose_name='Cost soni')),
                ('description', models.TextField(verbose_name='Cost haqida')),
                ('created_at', models.DateField(verbose_name='Cost sanasi')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_name_references', to='home.book_model', verbose_name='Cost nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Income_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Narxi')),
                ('quantity', models.IntegerField(verbose_name='Soni')),
                ('description', models.TextField(verbose_name='haqida')),
                ('created_at', models.DateField(verbose_name='sanasi')),
                ('sold_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sold_book_references', to='home.book_model')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(verbose_name='Output narxi')),
                ('description', models.TextField(verbose_name='Output haqida')),
                ('created_at', models.DateField(verbose_name='Output sanasi')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reference')),
            ],
        ),
        migrations.AddField(
            model_name='book_model',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_category_references', to='home.reference'),
        ),
        migrations.CreateModel(
            name='Staff_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Xodimning ism familiyasi')),
                ('birthday', models.DateField(verbose_name="Xodimning tug'ilgan sanasi")),
                ('phone_number', models.CharField(max_length=255, verbose_name='Xodimning telefon raqami')),
                ('added_at', models.DateField()),
                ('experience', models.FloatField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reference')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Narxi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.staff_model')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_work', models.IntegerField()),
                ('price', models.FloatField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.staff_model')),
            ],
        ),
    ]
